teuthology:
  postmerge:
    # Once can we make sure the distro kernels have included the fscrypt feature
    # or the ceph-fuse have supported the fscrypt feature we can remove this
    # restriction.
    - if not is_kupstream() then reject() end
overrides:
  kclient:
    mntopts: [test_dummy_encryption]
tasks:
- workunit:
- parallel:
   - user-workload
   - kclient-workload
user-workload:
  sequential:
  - ceph-fuse: [client.0]
  - workunit:
      subdir: fscrypt-share
      clients:
         client.0:
           - fs/fscrypt_protect.sh fuse
kclient-workload:
  sequential:
  - kclient: [client.1]
  - workunit:
      subdir: fscrypt-share
      clients:
         client.1:
           - fs/fscrypt_protect.sh kclient

