tasks:
- workunit:
    clients:
      client.0:
      - libcephfs/test_newops.sh
      client.1:
      - PATH=`echo $(mount | grep ' type ceph ' | awk '{print $3}')`/testdir
      - sudo mkdir $PATH
      - sudo setfattr -n ceph.dir.pin.random -v 0.5 $PATH
      - sudo getfattr -n ceph.dir.pin.random $PATH
      - sudo rmdir -rf $PATH
- print: "**** done libcephfs test"
