tasks:
- workunit:
    clients:
      client.0:
      - PATH=`echo $(mount | grep 'ceph-fuse' | awk '{print $3}')`/testdir
      - echo $?
      - sudo mkdir $PATH
      - echo $?
      - sudo setfattr -n ceph.dir.pin.random -v 0.5 $PATH
      - echo $?
      - sudo getfattr -n ceph.dir.pin.random $PATH
      - echo $?
      - sudo rmdir -rf $PATH
      - echo $?
- print: "**** done libcephfs test"
